// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cliente struct {
	Ativo bool
	ID    pgtype.UUID
	Cpf   pgtype.Text
	Email pgtype.Text
	Nome  pgtype.Text
}
